### ISSUE TITLE
Crash for CERN-EP publications

### ISSUE THREAD

**Issue by clelange** [clelange/cds_paper_bot#4]
```
2018-01-16 11:10:55,499 [35404] INFO     root: CERN-EP-2017-337 - published: 2018-01-15 19:11:48+00:00
2018-01-16 11:10:55,500 [35404] INFO     root: Processing images.
2018-01-16 11:10:55,502 [35404] CRITICAL root: Traceback (most recent call last):
  File "cds_paper_bot.py", line 399, in <module>
    main()
  File "cds_paper_bot.py", line 375, in main
    image_list = process_images(identifier, downloaded_image_list)
  File "cds_paper_bot.py", line 167, in process_images
    format='GIF-FI', duration=2, quantizer='nq', palettesize=256)
  File "/Users/clange/.ve/CDSPaperBot/lib/python3.6/site-packages/imageio/core/functions.py", line 313, in mimwrite
    raise ValueError('Numpy sequence must not be empty.')
ValueError: Numpy sequence must not be empty.
```

**Comment by clelange** [comment]
This seems to be an issue with the way things are posted on CDS, since the afore-mentioned publication is now fine and called CMS-HIN-16-014, https://cds.cern.ch/record/2300265.
